config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists, only: %i[show new create destroy] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  has_one_attached :image
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true
  validates :title, uniqueness: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[list new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.movie = @movie

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    List.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<div class="container body">
  <div class="lists-header d-flex justify-content-between align-items-center mb-3">
    <h1><%= @list.name.capitalize %> bookmarks</h1>
    <%= link_to 'New bookmark', new_list_bookmark_path, class: "btn btn-primary" %>
  </div>

  <section class="list-body">
    <% @bookmarks.each do |bookmark| %>
      <div class="card mb-3">
        <%= link_to list_bookmarks_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Sure?" } do %>
          <div class="card-body">
            <%= bookmark.comment %>
          </div>
        <% end %>
      </div>
    <% end %>
  </section>
</div>

app/views/bookmarks/new.html.erb
<div class="container body">
  <h1 class="mb-3">Add a movie to <%= @list.name %></h1>
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.button :submit, 'Add movie', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% unless request.path == "/" || request.path.match?(/\/lists\/\d+$/) %>
      <nav class="navbar sticky-top bg-light">
        <div class="container">
          <%= link_to 'Home', root_path, class: "navbar-brand" %>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="mb-4 d-flex p-4 custom-banner" style="background-color: #253D56">
  <div class="container d-flex justify-content-between flex-column" data-controller="banner">
    <div>
      <%= link_to root_path, class: "navbar-brand", class: "d-flex align-items-center banner-link" do %>
        <i class="fa-solid fa-clapperboard"></i>
        <p class="m-0">Home</p>
      <% end %>
    </div>
    <div class="banner-body">
      <h1>Movies list</h1>
      <p>Add a new movies list!</p>
      <%= link_to 'New list', new_list_path, class: "btn btn-home" %>
    </div>
  </div>
</div>

<div class="container body">
  <section class="list-body">
    <% @lists.each do |list| %>
      <div class="card mb-3 d-flex justify-content-between flex-row align-items-center">
        <%= link_to list_path(list), class: "flex-grow-1" do %>
        <div class="card-body d-flex justify-content-between">
          <%= list.name.capitalize %>
        </div>
        <% end %>
        <%= link_to list_path(list), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash-can ms-3 me-3"></i>
        <% end %>
      </div>
    <% end %>
  </section>
</div>

app/views/lists/new.html.erb
<div class="container body">
  <h1 class="mb-3">Create a movie list</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="mb-4 d-flex p-4 custom-banner" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url('<%= cl_image_path @list.image.key, crop: :fill, gravity: :auto %>')">
  <div class="container d-flex justify-content-between flex-column">
    <div>
      <%= link_to root_path, class: "navbar-brand", class: "d-flex align-items-center banner-link" do %>
        <i class="fa-solid fa-clapperboard"></i>
        <p class="m-0">Home</p>
      <% end %>
    </div>
    <div class="banner-body">
      <h1><%= @list.name.capitalize %> movies list</h1>
      <p>Add movies to this list</p>
      <%= link_to 'Add a movie', new_list_bookmark_path(@list), class: "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="container body">
  <div class="row row-cols-1 row-cols-md-2 g-4 mt-4">
    <% @bookmarks.each do |bookmark| %>
      <div class="col movie">
        <div class="card">
          <div style="background-image: url('<%= bookmark.movie.poster_url %>')" class="movie-cover"></div>
          <div class="card-body">
            <div class="card-body-header d-flex justify-content-between">
              <h5 class="card-title"><%= bookmark.movie.title %></h5>
              <p><%= bookmark.movie.rating %> <i class="fa-solid fa-star"></i></p>
            </div>
            <p class="card-text"><%= bookmark.movie.overview %></p>
            <div class="d-flex justify-content-between">
              <div>
                <p class="card-text"><i class="fa-solid fa-quote-left"></i> <%= bookmark.comment %></p>
              </div>
              <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                <i class="fa-solid fa-trash-can"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>